# Generated by Django 5.1.2 on 2024-10-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_accountcreationattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="Untitled", max_length=255),
        ),
    ]
