# Generated by Django 5.1.2 on 2024-10-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_image_alter_post_video_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="description",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
